### ISSUE TITLE
PostgreSQL error in local_obf upgrade

### ISSUE THREAD

**Issue by anieminen** [openbadgefactory/obf-moodle#22]
Hi,

Upgrading to latest version throws a database error with PostgreSQL, below is the debug info. It seems that `INSERT IGNORE INTO...` database query is only compatible with MySQL. 

> Debug info: ERROR: syntax error at or near "IGNORE"
LINE 1: INSERT IGNORE INTO mdl_local_obf_history_emails (`user_id`, ...
^
INSERT IGNORE INTO mdl_local_obf_history_emails (`user_id`, `email`, `timestamp`)
SELECT id, email, timemodified FROM mdl_user WHERE deleted = 0
[array (
)]
Error code: dmlwriteexception
Stack trace:
    line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
    line 248 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
    line 708 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    line 51 of /local/obf/db/upgrade.php: call to pgsql_native_moodle_database->execute()
    line 632 of /lib/upgradelib.php: call to xmldb_local_obf_upgrade()
    line 1857 of /lib/upgradelib.php: call to upgrade_plugins()
    line 694 of /admin/index.php: call to upgrade_noncore()

**Comment by ajk** [comment]
Fixed in 57f992f5221
