### ISSUE TITLE
Badge awarding rules can not be created

### ISSUE THREAD

**Issue by ClaudeUX** [openbadgefactory/obf-moodle#25]
Hi,

I am running a brand new Moodle Site in 3.10+.
So far connection to OBF worked fine and badges are shown.
But I am unable to create an awarding rule on badges. When selecting the method by which the badge will be earned "Completing a set of courses" or "Completing a set of activities" nothing happens. When selecting the "Profile completion" method the options load properly.
When selecting one of the other 2 and saving changes, I get an error 500 (obviously).

Thanks for a hint or fix.
Claude

**Comment by heidiwik** [comment]
Hi ClaudeUX,
There was a bug which caused problems with awarding rule creation in Moodle 3.10. This is now fixed. Thank you for reporting!

**Comment by heidiwik** [comment]
bug fixed
