### ISSUE TITLE
Student getting error in Moodle

### ISSUE THREAD

**Issue by simpasami** [openbadgefactory/obf-moodle#28]
**Class 'core_user\fields' not found**

line 745 of /local/obf/class/client.php: Error thrown
line 405 of /local/obf/class/badge.php: call to obf_client->issue_badge()
line 158 of /local/obf/class/assertion.php: call to obf_badge->issue()
line 124 of /local/obf/issue.php: call to obf_assertion->process()

Moodle is 3.9.19, Pluging is 0.6.0 (2022112400)

**Comment by simpasami** [comment]
![DataImage1](https://user-images.githubusercontent.com/117338882/213984500-7400e64f-66b6-416b-ac45-a05c80c9d60b.png)

**Comment by simpasami** [comment]
same issue in this tool also: https://github.com/elearningsoftware/moodle-mod_journal/commit/e5675ced1f9b78df2fc524b932dace0a87c5cbf2 
https://github.com/elearningsoftware/moodle-mod_journal/pull/79

**Comment by montanae** [comment]
Same problem with moodle 3.9.18 Pluging is 0.6.0 (2022112400)
Is it possible to downgrade to an older version of the plugin ?
