### ISSUE TITLE
Issue with courseuserbadges.php on big moodle site -> history more than 1000 entries 

### ISSUE THREAD

**Issue by winnidat** [openbadgefactory/obf-moodle#31]
There is in issue when you want to view the courseuserbadges history: 

I guess the problem is that moodle gets the first 1000 entries
with the API call GET /v1/event/{client_id} and compares the result with the course_ids so no badges are shown on the courseuserbadges if you are currently in the range of 5000-6000 badges.

https://openbadgefactory.com/static/doc/obf-api-v1.pdf -> here on page 18 limit is 1000.

Possible fix: 

- increase allowed limit
- make a more specific API request
- send back an indicator that there are more entries and iterate over requests

Best regards,
Thomas

**Comment by ajk** [comment]
Fixed in b0b0075
